<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="curriculum">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="datosPersonales">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="apellido" type="xs:string" />
                            <xs:element name="nacimineto" type="xs:gYear" />
                            <xs:element name="residencia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ciudad" type="xs:string" />
                                        <xs:element name="pais" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contacto">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="telefono" type="xs:string" />
                            <xs:element name="correo" type="xs:string"  />
                            <xs:element name="linkedin" type="xs:string"  />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="carrera">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="descripcion" type="xs:string" />
                            <xs:element name="competencias" >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="competencia" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombreCom" type="xs:string" />
                                                    <xs:element name="nivel" type="xs:string" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="formaciones" >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="formacion" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulacion" type="xs:string" />
                                                    <xs:element name="centro" type="xs:string" />
                                                    <xs:element name="fechaFin" type="xs:gYear" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="experiencias" >
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="experiencia" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="puesto" type="xs:string" />
                                                    <xs:element name="empresa" type="xs:string" />
                                                    <xs:element name="fechaIni" type="xs:gYear" />
                                                    <xs:element name="fechaFinal" type="xs:gYear" />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
